"""Add marking_mode to Test

Revision ID: add_marking_mode_to_test
Revises: ec929b113aa9
Create Date: 2026-07-14 11:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_marking_mode_to_test'
down_revision: Union[str, Sequence[str], None] = '003_add_password_reset_requests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type for marking_mode
    marking_mode_enum = postgresql.ENUM('auto', 'manual', name='markingmode')
    marking_mode_enum.create(op.get_bind())
    
    # Add column with default value
    op.add_column('tests', sa.Column('marking_mode', sa.Enum('auto', 'manual', name='markingmode'), nullable=True, server_default='auto'))
    
    # Update existing rows to have 'auto' as default
    op.execute("UPDATE tests SET marking_mode = 'auto' WHERE marking_mode IS NULL")
    
    # Make column non-nullable
    op.alter_column('tests', 'marking_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'marking_mode')
    postgresql.ENUM(name='markingmode').drop(op.get_bind())
    # ### end Alembic commands ###
